blank_issues_enabled: false
contact_links:
  - name: ðŸ—¨ Discussions
    url: https://github.com/revanced/revanced-suggestions/discussions
    about: Have something unspecific to ReVanced Patches template in mind? Search for or start a new discussion!